name: Build RPM and DEB

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies for RPM and DEB
      run: |
        sudo apt-get update
        sudo apt-get install rpm dpkg-dev build-essential

    - name: Build RPM
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp count_files.sh ~/rpmbuild/SOURCES/
        rpmbuild -ba --define "_topdir ~/rpmbuild" file-counter.spec

    - name: Build DEB
      run: |
        mkdir -p file-counter-1.0/usr/local/bin
        cp count_files.sh file-counter-1.0/usr/local/bin/
        chmod 755 file-counter-1.0/usr/local/bin/count_files.sh
        mkdir -p file-counter-1.0/DEBIAN
        echo "Package: file-counter" > file-counter-1.0/DEBIAN/control
        echo "Version: 1.0" >> file-counter-1.0/DEBIAN/control
        echo "Section: base" >> file-counter-1.0/DEBIAN/control
        echo "Priority: optional" >> file-counter-1.0/DEBIAN/control
        echo "Architecture: all" >> file-counter-1.0/DEBIAN/control
        echo "Maintainer: Serhii> file-counter-1.0/DEBIAN/control
        echo "Description: A script to count files in /etc excluding directories and symlinks" >> file-counter-1.0/DEBIAN/control
        dpkg-deb --build file-counter-1.0

